name: Convert and Deploy HTML

on:
  push:
    branches:
      - main
    paths:
      - '**.ipynb'  # Trigger the workflow on changes to any Jupyter Notebook
      - 'requirements.txt'  # Also trigger on changes to the requirements file

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write


    steps:
    - uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install dependencies, assuming nbconvert is listed in requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Convert Notebook to HTML
    - name: Convert Notebook to HTML
      run: |
        jupyter nbconvert --to html --execute --output-dir=. "Final_Project_Kalra_Kheria_Shah.ipynb"

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: false
